GET http://localhost:5003/categories

### 
POST http://localhost:5004/products
Content-Type: application/json

{  
  "name":"Ürün 1",
  "categoryId":"019c2cc8-42b7-73c1-8c4a-32a734044835"
}

###
GET http://localhost:5004/products

###
GET http://localhost:5004/test